name: Test PowerShell on Ubuntu
on: [push, pull_request]

jobs:
  pester-tests:
    name: Run Pester tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester *.Tests.ps1 -Passthru